[pytest]
asyncio_mode = auto
python_files = test_*.py
addopts = --cov=. --cov-report=term-missing --cov-config=pytest.ini

[coverage:run]
omit =
    tests/*
    */tests/*
    conftest.py
    *test_db.py
    init_db.py